name: Deploy to Coolify

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy:
        description: "Deploy to Coolify"
        required: false
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Coolify
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            -H "Content-Type: application/json" \
            "$ {{ secrets.COOLIFY_DEPLOY_URL }}"